'use strict';

module.exports = {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  res: {
    _readableState: {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: {
        encoding: 'utf8',
        surrogateSize: 3,
        charBuffer: '<Buffer 52 a1 85 01 01 00>',
        charReceived: 0,
        charLength: 0
      },
      encoding: 'utf8'
    },
    readable: false,
    domain: null,
    _maxListeners: undefined,
    socket: {
      _connecting: false,
      _hadError: false,
      _handle: null,
      _parent: null,
      _host: 'localhost',
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      domain: null,
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: {
          next: {next: null, entry: null, finish: [Function]},
          entry: null,
          finish: [Function]
        }
      },
      writable: false,
      allowHalfOpen: false,
      destroyed: true,
      bytesRead: 210,
      _bytesDispatched: 223,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: {
        domain: null,
        _events: {drain: [Function], error: [Function], response: [Function]},
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {'content-length': false},
        _contentLength: 29,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
        _headers: {
          host: 'localhost:3000',
          'accept-encoding': 'gzip, deflate',
          'user-agent': 'node-superagent/1.8.3',
          'content-type': 'application/json',
          'content-length': 29
        },
        _headerNames: {
          host: 'Host',
          'accept-encoding': 'Accept-Encoding',
          'user-agent': 'User-Agent',
          'content-type': 'Content-Type',
          'content-length': 'Content-Length'
        },
        _onPendingData: null,
        agent: {
          domain: null,
          _events: {free: [Function]},
          _eventsCount: 1,
          _maxListeners: undefined,
          defaultPort: 80,
          protocol: 'http:',
          options: {path: null},
          requests: {},
          sockets: {'localhost:3000:': [[Circular]]},
          freeSockets: {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256
        },
        socketPath: undefined,
        method: 'POST',
        path: '/?since=blahblah',
        parser: null,
        res: [Circular]
      },
      read: [Function],
      _consuming: true,
      _idleNext: null,
      _idlePrev: null,
      _idleTimeout: -1
    },
    connection: {
      _connecting: false,
      _hadError: false,
      _handle: null,
      _parent: null,
      _host: 'localhost',
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      domain: null,
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: {
          next: {next: null, entry: null, finish: [Function]},
          entry: null,
          finish: [Function]
        }
      },
      writable: false,
      allowHalfOpen: false,
      destroyed: true,
      bytesRead: 210,
      _bytesDispatched: 223,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: {
        domain: null,
        _events: {drain: [Function], error: [Function], response: [Function]},
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {'content-length': false},
        _contentLength: 29,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
        _headers: {
          host: 'localhost:3000',
          'accept-encoding': 'gzip, deflate',
          'user-agent': 'node-superagent/1.8.3',
          'content-type': 'application/json',
          'content-length': 29
        },
        _headerNames: {
          host: 'Host',
          'accept-encoding': 'Accept-Encoding',
          'user-agent': 'User-Agent',
          'content-type': 'Content-Type',
          'content-length': 'Content-Length'
        },
        _onPendingData: null,
        agent: {
          domain: null,
          _eventsCount: 1,
          _maxListeners: undefined,
          defaultPort: 80,
          protocol: 'http:',
          options: {path: null},
          requests: {},
          sockets: {'localhost:3000:': [[Circular]]},
          freeSockets: {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256
        },
        socketPath: undefined,
        method: 'POST',
        path: '/?since=blahblah',
        parser: null,
        res: [Circular]
      },
      read: [Function],
      _consuming: true,
      _idleNext: null,
      _idlePrev: null,
      _idleTimeout: -1
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'content-type': 'application/json',
      date: 'Tue, 29 Mar 2016 03:12:33 GMT',
      connection: 'close',
      'transfer-encoding': 'chunked'
    },
    rawHeaders: ['Content-Type',
      'application/json',
      'Date',
      'Tue, 29 Mar 2016 03:12:33 GMT',
      'Connection',
      'close',
      'Transfer-Encoding',
      'chunked'],
    trailers: {},
    rawTrailers: [],
    upgrade: false,
    url: '',
    method: null,
    statusCode: 200,
    statusMessage: 'OK',
    client: {
      _connecting: false,
      _hadError: false,
      _handle: null,
      _parent: null,
      _host: 'localhost',
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      domain: null,
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: {
          next: {next: null, entry: null, finish: [Function]},
          entry: null,
          finish: [Function]
        }
      },
      writable: false,
      allowHalfOpen: false,
      destroyed: true,
      bytesRead: 210,
      _bytesDispatched: 223,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: {
        domain: null,
        _events: {drain: [Function], error: [Function], response: [Function]},
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {'content-length': false},
        _contentLength: 29,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
        _headers: {
          host: 'localhost:3000',
          'accept-encoding': 'gzip, deflate',
          'user-agent': 'node-superagent/1.8.3',
          'content-type': 'application/json',
          'content-length': 29
        },
        _headerNames: {
          host: 'Host',
          'accept-encoding': 'Accept-Encoding',
          'user-agent': 'User-Agent',
          'content-type': 'Content-Type',
          'content-length': 'Content-Length'
        },
        _onPendingData: null,
        agent: {
          domain: null,
          _events: {free: [Function]},
          _eventsCount: 1,
          _maxListeners: undefined,
          defaultPort: 80,
          protocol: 'http:',
          options: {path: null},
          requests: {},
          sockets: {'localhost:3000:': [[Circular]]},
          freeSockets: {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256
        },
        socketPath: undefined,
        method: 'POST',
        path: '/?since=blahblah',
        parser: null,
        res: [Circular]
      },
      read: [Function],
      _consuming: true,
      _idleNext: null,
      _idlePrev: null,
      _idleTimeout: -1
    },
    _consuming: true,
    _dumped: false,
    req: {
      domain: null,
      _events: {drain: [Function], error: [Function], response: [Function]},
      _eventsCount: 3,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedHeader: {'content-length': false},
      _contentLength: 29,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      connection: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
      _headers: {
        host: 'localhost:3000',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'node-superagent/1.8.3',
        'content-type': 'application/json',
        'content-length': 29
      },
      _headerNames: {
        host: 'Host',
        'accept-encoding': 'Accept-Encoding',
        'user-agent': 'User-Agent',
        'content-type': 'Content-Type',
        'content-length': 'Content-Length'
      },
      _onPendingData: null,
      agent: {
        domain: null,
        _events: {free: [Function]},
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: {path: null},
        requests: {},
        sockets: {
          'localhost:3000:': [{
            _connecting: false,
            _hadError: false,
            _handle: null,
            _parent: null,
            _host: 'localhost',
            _readableState: {
              objectMode: false,
              highWaterMark: 16384,
              buffer: [],
              length: 0,
              pipes: null,
              pipesCount: 0,
              flowing: true,
              ended: false,
              endEmitted: false,
              reading: true,
              sync: false,
              needReadable: true,
              emittedReadable: false,
              readableListening: false,
              resumeScheduled: false,
              defaultEncoding: 'utf8',
              ranOut: false,
              awaitDrain: 0,
              readingMore: false,
              decoder: null,
              encoding: null
            },
            readable: false,
            domain: null,
            _eventsCount: 8,
            _maxListeners: undefined,
            _writableState: {
              objectMode: false,
              highWaterMark: 16384,
              needDrain: false,
              ending: true,
              ended: true,
              finished: true,
              decodeStrings: false,
              defaultEncoding: 'utf8',
              length: 0,
              writing: false,
              corked: 0,
              sync: false,
              bufferProcessing: false,
              onwrite: [Function],
              writecb: null,
              writelen: 0,
              bufferedRequest: null,
              lastBufferedRequest: null,
              pendingcb: 0,
              prefinished: true,
              errorEmitted: false,
              bufferedRequestCount: 0,
              corkedRequestsFree: {
                next: {next: null, entry: null, finish: [Function]},
                entry: null,
                finish: [Function]
              }
            },
            writable: false,
            allowHalfOpen: false,
            destroyed: true,
            bytesRead: 210,
            _bytesDispatched: 223,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [Circular],
            read: [Function],
            _consuming: true,
            _idleNext: null,
            _idlePrev: null,
            _idleTimeout: -1
          }]
        },
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256
      },
      socketPath: undefined,
      method: 'POST',
      path: '/?since=blahblah',
      parser: null,
      res: [Circular]
    },
    text: '{"error":[],"result":{"XXBTZEUR":[],"last":1427617277683000000}}',
    read: [Function],
    body: {
      error: [],
      result: {XXBTZEUR: [], last: 1427617277683000000}
    }
  },
  request: {
    domain: null,
    _eventsCount: 1,
    _maxListeners: undefined,
    _agent: false,
    _formData: null,
    method: 'POST',
    url: 'http://localhost:3000',
    _header: {
      'user-agent': 'node-superagent/1.8.3',
      'content-type': 'application/json'
    },
    header: {
      'User-Agent': 'node-superagent/1.8.3',
      'Content-Type': 'application/json'
    },
    writable: true,
    _redirects: 0,
    _maxRedirects: 5,
    cookies: '',
    qs: {since: 'blahblah'},
    qsRaw: [],
    _redirectList: [],
    _streamRequest: false,
    _data: {hello: 'this is from post'},
    req: {
      domain: null,
      _eventsCount: 3,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedHeader: {'content-length': false},
      _contentLength: 29,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      connection: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
      _headers: {
        host: 'localhost:3000',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'node-superagent/1.8.3',
        'content-type': 'application/json',
        'content-length': 29
      },
      _headerNames: {
        host: 'Host',
        'accept-encoding': 'Accept-Encoding',
        'user-agent': 'User-Agent',
        'content-type': 'Content-Type',
        'content-length': 'Content-Length'
      },
      _onPendingData: null,
      agent: {
        domain: null,
        _events: {free: [Function]},
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: {path: null},
        requests: {},
        sockets: {
          'localhost:3000:': [{
            _connecting: false,
            _hadError: false,
            _handle: null,
            _parent: null,
            _host: 'localhost',
            _readableState: {
              objectMode: false,
              highWaterMark: 16384,
              buffer: [],
              length: 0,
              pipes: null,
              pipesCount: 0,
              flowing: true,
              ended: false,
              endEmitted: false,
              reading: true,
              sync: false,
              needReadable: true,
              emittedReadable: false,
              readableListening: false,
              resumeScheduled: false,
              defaultEncoding: 'utf8',
              ranOut: false,
              awaitDrain: 0,
              readingMore: false,
              decoder: null,
              encoding: null
            },
            readable: false,
            domain: null,
            _eventsCount: 8,
            _maxListeners: undefined,
            _writableState: {
              objectMode: false,
              highWaterMark: 16384,
              needDrain: false,
              ending: true,
              ended: true,
              finished: true,
              decodeStrings: false,
              defaultEncoding: 'utf8',
              length: 0,
              writing: false,
              corked: 0,
              sync: false,
              bufferProcessing: false,
              onwrite: [Function],
              writecb: null,
              writelen: 0,
              bufferedRequest: null,
              lastBufferedRequest: null,
              pendingcb: 0,
              prefinished: true,
              errorEmitted: false,
              bufferedRequestCount: 0,
              corkedRequestsFree: {
                next: {next: null, entry: null, finish: [Function]},
                entry: null,
                finish: [Function]
              }
            },
            writable: false,
            allowHalfOpen: false,
            destroyed: true,
            bytesRead: 210,
            _bytesDispatched: 223,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [Circular],
            read: [Function],
            _consuming: true,
            _idleNext: null,
            _idlePrev: null,
            _idleTimeout: -1
          }]
        },
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256
      },
      socketPath: undefined,
      method: 'POST',
      path: '/?since=blahblah',
      parser: null,
      res: {
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: true,
          endEmitted: true,
          reading: false,
          sync: true,
          needReadable: false,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: {
            encoding: 'utf8',
            surrogateSize: 3,
            charBuffer: '<Buffer 52 a1 85 01 01 00>',
            charReceived: 0,
            charLength: 0
          },
          encoding: 'utf8'
        },
        readable: false,
        domain: null,

        _eventsCount: 4,
        _maxListeners: undefined,
        socket: {
          _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'localhost',
          _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: false,
          domain: null,

          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: {
              next: {next: null, entry: null, finish: [Function]},
              entry: null,
              finish: [Function]
            }
          },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 210,
          _bytesDispatched: 223,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1
        },
        connection: {
          _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'localhost',
          _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: false,
          domain: null,

          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: {
              next: {next: null, entry: null, finish: [Function]},
              entry: null,
              finish: [Function]
            }
          },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 210,
          _bytesDispatched: 223,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1
        },
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: {
          'content-type': 'application/json',
          date: 'Tue, 29 Mar 2016 03:12:33 GMT',
          connection: 'close',
          'transfer-encoding': 'chunked'
        },
        rawHeaders: ['Content-Type',
          'application/json',
          'Date',
          'Tue, 29 Mar 2016 03:12:33 GMT',
          'Connection',
          'close',
          'Transfer-Encoding',
          'chunked'],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: {
          _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'localhost',
          _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: false,
          domain: null,
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: {
              next: {next: null, entry: null, finish: [Function]},
              entry: null,
              finish: [Function]
            }
          },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 210,
          _bytesDispatched: 223,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1
        },
        _consuming: true,
        _dumped: false,
        req: [Circular],
        text: '{"error":[],"result":{"XXBTZEUR":[],"last":1427617277683000000}}',
        read: [Function],
        body: {
          error: [],
          result: {XXBTZEUR: [], last: 1427617277683000000}
        }
      }
    },
    protocol: 'http:',
    host: 'localhost:3000',
    _callback: [Function],
    res: {
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: {
          encoding: 'utf8',
          surrogateSize: 3,
          charBuffer: '<Buffer 52 a1 85 01 01 00>',
          charReceived: 0,
          charLength: 0
        },
        encoding: 'utf8'
      },
      readable: false,
      domain: null,

      _eventsCount: 4,
      _maxListeners: undefined,
      socket: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: {
          domain: null,
          _events: {drain: [Function], error: [Function], response: [Function]},
          _eventsCount: 3,
          _maxListeners: undefined,
          output: [],
          outputEncodings: [],
          outputCallbacks: [],
          outputSize: 0,
          writable: true,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          useChunkedEncodingByDefault: true,
          sendDate: false,
          _removedHeader: {'content-length': false},
          _contentLength: 29,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          socket: [Circular],
          connection: [Circular],
          _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
          _headers: {
            host: 'localhost:3000',
            'accept-encoding': 'gzip, deflate',
            'user-agent': 'node-superagent/1.8.3',
            'content-type': 'application/json',
            'content-length': 29
          },
          _headerNames: {
            host: 'Host',
            'accept-encoding': 'Accept-Encoding',
            'user-agent': 'User-Agent',
            'content-type': 'Content-Type',
            'content-length': 'Content-Length'
          },
          _onPendingData: null,
          agent: {
            domain: null,
            _events: {free: [Function]},
            _eventsCount: 1,
            _maxListeners: undefined,
            defaultPort: 80,
            protocol: 'http:',
            options: {path: null},
            requests: {},
            sockets: {'localhost:3000:': [[Circular]]},
            freeSockets: {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256
          },
          socketPath: undefined,
          method: 'POST',
          path: '/?since=blahblah',
          parser: null,
          res: [Circular]
        },
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      connection: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: {
          domain: null,
          _eventsCount: 3,
          _maxListeners: undefined,
          output: [],
          outputEncodings: [],
          outputCallbacks: [],
          outputSize: 0,
          writable: true,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          useChunkedEncodingByDefault: true,
          sendDate: false,
          _removedHeader: {'content-length': false},
          _contentLength: 29,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          socket: [Circular],
          connection: [Circular],
          _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
          _headers: {
            host: 'localhost:3000',
            'accept-encoding': 'gzip, deflate',
            'user-agent': 'node-superagent/1.8.3',
            'content-type': 'application/json',
            'content-length': 29
          },
          _headerNames: {
            host: 'Host',
            'accept-encoding': 'Accept-Encoding',
            'user-agent': 'User-Agent',
            'content-type': 'Content-Type',
            'content-length': 'Content-Length'
          },
          _onPendingData: null,
          agent: {
            domain: null,
            _eventsCount: 1,
            _maxListeners: undefined,
            defaultPort: 80,
            protocol: 'http:',
            options: {path: null},
            requests: {},
            sockets: {'localhost:3000:': [[Circular]]},
            freeSockets: {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256
          },
          socketPath: undefined,
          method: 'POST',
          path: '/?since=blahblah',
          parser: null,
          res: [Circular]
        },
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: {
        'content-type': 'application/json',
        date: 'Tue, 29 Mar 2016 03:12:33 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked'
      },
      rawHeaders: ['Content-Type',
        'application/json',
        'Date',
        'Tue, 29 Mar 2016 03:12:33 GMT',
        'Connection',
        'close',
        'Transfer-Encoding',
        'chunked'],
      trailers: {},
      rawTrailers: [],
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: {
          domain: null,
          _events: {drain: [Function], error: [Function], response: [Function]},
          _eventsCount: 3,
          _maxListeners: undefined,
          output: [],
          outputEncodings: [],
          outputCallbacks: [],
          outputSize: 0,
          writable: true,
          _last: true,
          chunkedEncoding: false,
          shouldKeepAlive: false,
          useChunkedEncodingByDefault: true,
          sendDate: false,
          _removedHeader: {'content-length': false},
          _contentLength: 29,
          _hasBody: true,
          _trailer: '',
          finished: true,
          _headerSent: true,
          socket: [Circular],
          connection: [Circular],
          _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
          _headers: {
            host: 'localhost:3000',
            'accept-encoding': 'gzip, deflate',
            'user-agent': 'node-superagent/1.8.3',
            'content-type': 'application/json',
            'content-length': 29
          },
          _headerNames: {
            host: 'Host',
            'accept-encoding': 'Accept-Encoding',
            'user-agent': 'User-Agent',
            'content-type': 'Content-Type',
            'content-length': 'Content-Length'
          },
          _onPendingData: null,
          agent: {
            domain: null,
            _events: {free: [Function]},
            _eventsCount: 1,
            _maxListeners: undefined,
            defaultPort: 80,
            protocol: 'http:',
            options: {path: null},
            requests: {},
            sockets: {'localhost:3000:': [[Circular]]},
            freeSockets: {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256
          },
          socketPath: undefined,
          method: 'POST',
          path: '/?since=blahblah',
          parser: null,
          res: [Circular]
        },
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      _consuming: true,
      _dumped: false,
      req: {
        domain: null,
        _events: {drain: [Function], error: [Function], response: [Function]},
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {'content-length': false},
        _contentLength: 29,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: {
          _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'localhost',
          _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: false,
          domain: null,

          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: {
              next: {next: null, entry: null, finish: [Function]},
              entry: null,
              finish: [Function]
            }
          },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 210,
          _bytesDispatched: 223,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1
        },
        connection: {
          _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'localhost',
          _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: false,
          domain: null,
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: {
              next: {next: null, entry: null, finish: [Function]},
              entry: null,
              finish: [Function]
            }
          },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 210,
          _bytesDispatched: 223,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1
        },
        _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
        _headers: {
          host: 'localhost:3000',
          'accept-encoding': 'gzip, deflate',
          'user-agent': 'node-superagent/1.8.3',
          'content-type': 'application/json',
          'content-length': 29
        },
        _headerNames: {
          host: 'Host',
          'accept-encoding': 'Accept-Encoding',
          'user-agent': 'User-Agent',
          'content-type': 'Content-Type',
          'content-length': 'Content-Length'
        },
        _onPendingData: null,
        agent: {
          domain: null,
          _eventsCount: 1,
          _maxListeners: undefined,
          defaultPort: 80,
          protocol: 'http:',
          options: {path: null},
          requests: {},
          sockets: {
            'localhost:3000:': [{
              _connecting: false,
              _hadError: false,
              _handle: null,
              _parent: null,
              _host: 'localhost',
              _readableState: {
                objectMode: false,
                highWaterMark: 16384,
                buffer: [],
                length: 0,
                pipes: null,
                pipesCount: 0,
                flowing: true,
                ended: false,
                endEmitted: false,
                reading: true,
                sync: false,
                needReadable: true,
                emittedReadable: false,
                readableListening: false,
                resumeScheduled: false,
                defaultEncoding: 'utf8',
                ranOut: false,
                awaitDrain: 0,
                readingMore: false,
                decoder: null,
                encoding: null
              },
              readable: false,

              _eventsCount: 8,
              _maxListeners: undefined,
              _writableState: {
                objectMode: false,
                highWaterMark: 16384,
                needDrain: false,
                ending: true,
                ended: true,
                finished: true,
                decodeStrings: false,
                defaultEncoding: 'utf8',
                length: 0,
                writing: false,
                corked: 0,
                sync: false,
                bufferProcessing: false,
                onwrite: [Function],
                writecb: null,
                writelen: 0,
                bufferedRequest: null,
                lastBufferedRequest: null,
                pendingcb: 0,
                prefinished: true,
                errorEmitted: false,
                bufferedRequestCount: 0,
                corkedRequestsFree: {
                  next: {next: null, entry: null, finish: [Function]},
                  entry: null,
                  finish: [Function]
                }
              },
              writable: false,
              allowHalfOpen: false,
              destroyed: true,
              bytesRead: 210,
              _bytesDispatched: 223,
              _sockname: null,
              _pendingData: null,
              _pendingEncoding: '',
              server: null,
              _server: null,
              parser: null,
              _httpMessage: [Circular],
              read: [Function],
              _consuming: true,
              _idleNext: null,
              _idlePrev: null,
              _idleTimeout: -1
            }]
          },
          freeSockets: {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256
        },
        socketPath: undefined,
        method: 'POST',
        path: '/?since=blahblah',
        parser: null,
        res: [Circular]
      },
      text: '{"error":[],"result":{"XXBTZEUR":[],"last":1427617277683000000}}',
      read: [Function],
      body: {
        error: [],
        result: {XXBTZEUR: [], last: 1427617277683000000}
      }
    },
    response: [Circular],
    _timeout: 0,
    called: true
  },
  req: {
    domain: null,
    _eventsCount: 3,
    _maxListeners: undefined,
    output: [],
    outputEncodings: [],
    outputCallbacks: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedHeader: {'content-length': false},
    _contentLength: 29,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: {
      _connecting: false,
      _hadError: false,
      _handle: null,
      _parent: null,
      _host: 'localhost',
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      domain: null,
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: {
          next: {next: null, entry: null, finish: [Function]},
          entry: null,
          finish: [Function]
        }
      },
      writable: false,
      allowHalfOpen: false,
      destroyed: true,
      bytesRead: 210,
      _bytesDispatched: 223,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      read: [Function],
      _consuming: true,
      _idleNext: null,
      _idlePrev: null,
      _idleTimeout: -1
    },
    connection: {
      _connecting: false,
      _hadError: false,
      _handle: null,
      _parent: null,
      _host: 'localhost',
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      domain: null,

      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: {
          next: {next: null, entry: null, finish: [Function]},
          entry: null,
          finish: [Function]
        }
      },
      writable: false,
      allowHalfOpen: false,
      destroyed: true,
      bytesRead: 210,
      _bytesDispatched: 223,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      read: [Function],
      _consuming: true,
      _idleNext: null,
      _idlePrev: null,
      _idleTimeout: -1
    },
    _header: 'POST /?since=blahblah HTTP/1.1\r\nHost: localhost:3000\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.8.3\r\nContent-Type: application/json\r\nContent-Length: 29\r\nConnection: close\r\n\r\n',
    _headers: {
      host: 'localhost:3000',
      'accept-encoding': 'gzip, deflate',
      'user-agent': 'node-superagent/1.8.3',
      'content-type': 'application/json',
      'content-length': 29
    },
    _headerNames: {
      host: 'Host',
      'accept-encoding': 'Accept-Encoding',
      'user-agent': 'User-Agent',
      'content-type': 'Content-Type',
      'content-length': 'Content-Length'
    },
    _onPendingData: null,
    agent: {
      domain: null,
      _events: {free: [Function]},
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: {path: null},
      requests: {},
      sockets: {
        'localhost:3000:': [{
          _connecting: false,
          _hadError: false,
          _handle: null,
          _parent: null,
          _host: 'localhost',
          _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: false,
          domain: null,
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: true,
            ended: true,
            finished: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: true,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: {
              next: {next: null, entry: null, finish: [Function]},
              entry: null,
              finish: [Function]
            }
          },
          writable: false,
          allowHalfOpen: false,
          destroyed: true,
          bytesRead: 210,
          _bytesDispatched: 223,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: null,
          _server: null,
          parser: null,
          _httpMessage: [Circular],
          read: [Function],
          _consuming: true,
          _idleNext: null,
          _idlePrev: null,
          _idleTimeout: -1
        }]
      },
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256
    },
    socketPath: undefined,
    method: 'POST',
    path: '/?since=blahblah',
    parser: null,
    res: {
      _readableState: {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: {
          encoding: 'utf8',
          surrogateSize: 3,
          charBuffer: '<Buffer 52 a1 85 01 01 00>',
          charReceived: 0,
          charLength: 0
        },
        encoding: 'utf8'
      },
      readable: false,
      domain: null,
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      connection: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: {
        'content-type': 'application/json',
        date: 'Tue, 29 Mar 2016 03:12:33 GMT',
        connection: 'close',
        'transfer-encoding': 'chunked'
      },
      rawHeaders: ['Content-Type',
        'application/json',
        'Date',
        'Tue, 29 Mar 2016 03:12:33 GMT',
        'Connection',
        'close',
        'Transfer-Encoding',
        'chunked'],
      trailers: {},
      rawTrailers: [],
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          defaultEncoding: 'utf8',
          ranOut: false,
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: false,
        domain: null,

        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: {
          objectMode: false,
          highWaterMark: 16384,
          needDrain: false,
          ending: true,
          ended: true,
          finished: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: true,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: {
            next: {next: null, entry: null, finish: [Function]},
            entry: null,
            finish: [Function]
          }
        },
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 210,
        _bytesDispatched: 223,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1
      },
      _consuming: true,
      _dumped: false,
      req: [Circular],
      text: '{"error":[],"result":{"XXBTZEUR":[],"last":1427617277683000000}}',
      read: [Function],
      body: {
        error: [],
        result: {XXBTZEUR: [], last: 1427617277683000000}
      }
    }
  },
  links: {},
  text: '{"error":[],"result":{"XXBTZEUR":[],"last":1427617277683000000}}',
  body: {
    error: [],
    result: {XXBTZEUR: [], last: 1427617277683000000}
  },
  files: {},
  buffered: true,
  headers: {
    'content-type': 'application/json',
    date: 'Tue, 29 Mar 2016 03:12:33 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  header: {
    'content-type': 'application/json',
    date: 'Tue, 29 Mar 2016 03:12:33 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
  type: 'application/json',
  redirects: []
};